notifications:
  email:
      - cwelsh2@uw.edu
branches:
  only:
    - master
    - develop
    - travis-tests
services: docker
jobs:
  include:
    - stage: New build script
    - name: "Linux"
    - before_install:
        - docker pull ciaranwelsh/ubuntu-base
      script:
        - docker run ciaranwelsh/ubuntu-base /bin/sh -c "wget https://raw.githubusercontent.com/CiaranWelsh/libroadrunner-deps/master/roadrunner_deps_build.py; python roadrunner_deps_build.py /libroadrunner-deps-install-docker"

# These are placeholders: still need to implement since docker containers are harder to configure for mac and windows
#    - name : "Mac"
#    - name : "Windows"