sudo: required
dist: trusty

language: cpp

notifications:
  email:
      - cwelsh2@uw.edu

compiler: gcc

branches:
  only:
    - master

services: docker

before_install:
  - docker pull ciaranwelsh/ubuntu-base
  - docker run ciaranwelsh/ubuntu-base /bin/sh -c "wget
  -